# Generated by Django 3.2.12 on 2022-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user_default.png', null=True, upload_to='profiles/'),
        ),
    ]
