# Generated by Django 3.2.12 on 2022-07-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220728_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='vote',
            new_name='value',
        ),
    ]
